const templates = [
  {
    id: 'fin-education',
    name: 'Financial Education Q&A',
    description: 'Personal finance, investing, budgeting, credit management, and retirement planning questions.',
    category: 'financial',
    rating: 4.9,
    downloads: 12500,
    topics: ['Personal Finance', 'Investing', 'Credit & Debt', 'Retirement'],
    featured: true,
  },
  {
    id: 'healthcare-clinical',
    name: 'Clinical Knowledge Base',
    description: 'Medical terminology, symptoms, treatments, and healthcare procedures for training medical AI.',
    category: 'healthcare',
    rating: 4.8,
    downloads: 8700,
    topics: ['Medical Terms', 'Symptoms', 'Treatments', 'Procedures'],
    featured: true,
  },
  {
    id: 'legal-contracts',
    name: 'Legal Document Analysis',
    description: 'Contract clauses, legal terminology, compliance requirements, and case law summaries.',
    category: 'legal',
    rating: 4.7,
    downloads: 6300,
    topics: ['Contracts', 'Compliance', 'Legal Terms', 'Case Law'],
    featured: false,
  },
  {
    id: 'tech-programming',
    name: 'Programming Q&A',
    description: 'Code explanations, debugging help, best practices, and algorithm discussions.',
    category: 'technology',
    rating: 4.9,
    downloads: 15200,
    topics: ['Python', 'JavaScript', 'Algorithms', 'Best Practices'],
    featured: true,
  },
  {
    id: 'science-research',
    name: 'Scientific Research Assistant',
    description: 'Research methodology, experiment design, data analysis, and academic writing.',
    category: 'science',
    rating: 4.6,
    downloads: 4500,
    topics: ['Methodology', 'Data Analysis', 'Papers', 'Citations'],
    featured: false,
  },
  {
    id: 'edu-tutoring',
    name: 'Educational Tutoring',
    description: 'Math, science, language arts explanations suitable for K-12 and college students.',
    category: 'education',
    rating: 4.8,
    downloads: 9800,
    topics: ['Math', 'Science', 'English', 'History'],
    featured: false,
  },
];

module.exports = {
  templates,
};
