const templates = [
  {
    id: 'fin-education',
    name: 'Financial Education Q&A',
    description: 'Personal finance, investing, budgeting, credit management, and retirement planning questions.',
    category: 'financial',
    rating: 4.9,
    downloads: 12500,
    topics: ['Personal Finance', 'Investing', 'Credit & Debt', 'Retirement'],
    featured: true,
    language: 'en',
  },
  {
    id: 'healthcare-clinical',
    name: 'Clinical Knowledge Base',
    description: 'Medical terminology, symptoms, treatments, and healthcare procedures for training medical AI.',
    category: 'healthcare',
    rating: 4.8,
    downloads: 8700,
    topics: ['Medical Terms', 'Symptoms', 'Treatments', 'Procedures'],
    featured: true,
    language: 'en',
  },
  {
    id: 'legal-contracts',
    name: 'Legal Document Analysis',
    description: 'Contract clauses, legal terminology, compliance requirements, and case law summaries.',
    category: 'legal',
    rating: 4.7,
    downloads: 6300,
    topics: ['Contracts', 'Compliance', 'Legal Terms', 'Case Law'],
    featured: false,
    language: 'en',
  },
  {
    id: 'tech-programming',
    name: 'Programming Q&A',
    description: 'Code explanations, debugging help, best practices, and algorithm discussions.',
    category: 'technology',
    rating: 4.9,
    downloads: 15200,
    topics: ['Python', 'JavaScript', 'Algorithms', 'Best Practices'],
    featured: true,
    language: 'en',
  },
  {
    id: 'science-research',
    name: 'Scientific Research Assistant',
    description: 'Research methodology, experiment design, data analysis, and academic writing.',
    category: 'science',
    rating: 4.6,
    downloads: 4500,
    topics: ['Methodology', 'Data Analysis', 'Papers', 'Citations'],
    featured: false,
    language: 'en',
  },
  {
    id: 'edu-tutoring',
    name: 'Educational Tutoring',
    description: 'Math, science, language arts explanations suitable for K-12 and college students.',
    category: 'education',
    rating: 4.8,
    downloads: 9800,
    topics: ['Math', 'Science', 'English', 'History'],
    featured: false,
    language: 'en',
  },
  {
    id: 'customer-support',
    name: 'Customer Support Q&A',
    description: 'Help desk responses, troubleshooting guides, and customer service dialogue for support teams.',
    category: 'customer_support',
    rating: 4.7,
    downloads: 11200,
    topics: ['Troubleshooting', 'Returns', 'Account Issues', 'Product Help'],
    featured: true,
    language: 'en',
  },
  {
    id: 'ecommerce-products',
    name: 'E-commerce Product Data',
    description: 'Product descriptions, reviews, FAQ pairs, and catalog data for online retail.',
    category: 'ecommerce',
    rating: 4.5,
    downloads: 7800,
    topics: ['Product Descriptions', 'Reviews', 'FAQ', 'Catalog'],
    featured: false,
    language: 'en',
  },
  {
    id: 'realestate-listings',
    name: 'Real Estate Listings',
    description: 'Property descriptions, market analysis, neighborhood guides, and buyer Q&A.',
    category: 'realestate',
    rating: 4.4,
    downloads: 3200,
    topics: ['Property Listings', 'Market Analysis', 'Neighborhoods', 'Mortgages'],
    featured: false,
    language: 'en',
  },
  {
    id: 'gaming-dialogue',
    name: 'Gaming NPC Dialogue',
    description: 'NPC conversations, quest descriptions, item lore, and game world building text.',
    category: 'gaming',
    rating: 4.6,
    downloads: 5600,
    topics: ['NPC Dialogue', 'Quests', 'Item Lore', 'World Building'],
    featured: false,
    language: 'en',
  },
  {
    id: 'marketing-copy',
    name: 'Marketing & Advertising Copy',
    description: 'Ad copy, social media posts, email campaigns, and brand messaging.',
    category: 'marketing',
    rating: 4.7,
    downloads: 9100,
    topics: ['Ad Copy', 'Social Media', 'Email Campaigns', 'Brand Voice'],
    featured: true,
    language: 'en',
  },
  {
    id: 'hr-job-descriptions',
    name: 'Human Resources Data',
    description: 'Job descriptions, interview questions, performance reviews, and HR policy documents.',
    category: 'hr',
    rating: 4.5,
    downloads: 4100,
    topics: ['Job Descriptions', 'Interview Questions', 'Performance Reviews', 'Policies'],
    featured: false,
    language: 'en',
  },
  {
    id: 'news-journalism',
    name: 'News & Journalism',
    description: 'Article summaries, fact-check datasets, headline generation, and news Q&A.',
    category: 'news',
    rating: 4.3,
    downloads: 2800,
    topics: ['Article Summaries', 'Fact Checking', 'Headlines', 'News Q&A'],
    featured: false,
    language: 'en',
  },
  {
    id: 'cybersecurity-threats',
    name: 'Cybersecurity Intelligence',
    description: 'Threat descriptions, incident reports, vulnerability analysis, and security Q&A.',
    category: 'cybersecurity',
    rating: 4.8,
    downloads: 6700,
    topics: ['Threat Analysis', 'Incident Reports', 'Vulnerabilities', 'Best Practices'],
    featured: false,
    language: 'en',
  },
  {
    id: 'travel-guides',
    name: 'Travel & Hospitality',
    description: 'Destination guides, hotel reviews, itinerary planning, and travel tips.',
    category: 'travel',
    rating: 4.4,
    downloads: 3900,
    topics: ['Destinations', 'Hotels', 'Itineraries', 'Travel Tips'],
    featured: false,
    language: 'en',
  },
  {
    id: 'food-recipes',
    name: 'Food & Recipes',
    description: 'Recipes, restaurant reviews, nutrition information, and cooking techniques.',
    category: 'food',
    rating: 4.6,
    downloads: 5200,
    topics: ['Recipes', 'Restaurant Reviews', 'Nutrition', 'Cooking Techniques'],
    featured: false,
    language: 'en',
  },
  {
    id: 'code-generation',
    name: 'Code Generation & Review',
    description: 'Code snippets, code review comments, bug fix examples, and API usage patterns.',
    category: 'technology',
    rating: 4.9,
    downloads: 18500,
    topics: ['Code Snippets', 'Code Review', 'Bug Fixes', 'API Patterns'],
    featured: true,
    language: 'en',
  },
  {
    id: 'medical-research',
    name: 'Medical Research Papers',
    description: 'Clinical trial summaries, drug interaction data, medical case studies, and research abstracts.',
    category: 'healthcare',
    rating: 4.7,
    downloads: 7200,
    topics: ['Clinical Trials', 'Drug Interactions', 'Case Studies', 'Abstracts'],
    featured: false,
    language: 'en',
  },
];

module.exports = {
  templates,
};
