name: Client CI

on:
  push:
    paths:
      - "website/client/**"
      - ".github/workflows/client.yml"
  pull_request:
    paths:
      - "website/client/**"
      - ".github/workflows/client.yml"

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website/client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/client/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
